# ==============================================================
# = Config Server Versione Base
# = PROFILO GIT
# ==============================================================

spring:
  config:
    activate:
      on-profile: git
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: file:/Users/antonio.carnevale/Documents/git-config-repository