# ==============================================================
# = Config Server Versione Base
# = PROFILO GITHUB
# ==============================================================

spring:
  config:
    activate:
      on-profile: github
  application:
    name: config-server-github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Antocar98/priceart-config.git
          username: Antocar98
          password: ENC(5p5g0IZKNz4isfXJfw8BWvT11+2Eyxkn46/31zMOJO/9n7NIzPI3x/hb6GPMCNgiYfKBUBaOzIo=) #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
          timeout: 5 #in secondi
          cloneOnStart: true
          default-label: main